name: tensorflow-development
channels:
  - anaconda
  - conda-forge
  - defaults

dependencies:
  - python=3.7
  - numpy
  - matplotlib
  - pandas
  - tensorflow
  - notebook
  - nb_conda_kernels
  - jupyter_contrib_nbextensions
